[package]
name = "advent2019_day-2"
version = "0.1.0"
authors = ["Paul Doyle <pauldoyle22@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.5"